n=int(input())
z=1
while(z<=n):
    k=0
    if(n%z==0):
        j=1
        while(j<=z):
            if(z%j==0):
                k=k+1
            j=j+1
        if(k==2):
            print(z)
    z=z+1
